name: Continuous Deployment to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }} 

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push school image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: nishant0328/argocd-app:${{ github.sha }}

      - name: Clone staging-ops repo, update image tags, and push tags
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/Nishant-28/argocd-app.git
          
          sed -i 's|image: nishant0328/argocd-app:.*|image: nishant0328/argocd-app:${{ github.sha }}|' manifest.yml
          
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update server image tags to ${{ github.sha }}"
          git push https://${PAT}@github.com/Nishant-28/argocd-app.git main